version: "3.8"
services:
  dev-db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: graphql-boilerplate
      POSTGRES_USER: graphql-boilerplate
      POSTGRES_DB: graphql-boilerplate

  test-db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: graphql-boilerplate-test
      POSTGRES_USER: graphql-boilerplate-test
      POSTGRES_DB: graphql-boilerplate-test

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  test-redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "63791:63791"
    environment:
      - REDIS_REPLICATION_MODE=master
