export const LOGGING_LEVEL = "LOGGING_LEVEL";
export const API_PORT = "API_PORT";
export const IS_PRODUCTION = "IS_PRODUCTION";
export const API_CORS_ENDPOINT = "API_CORS_ENDPOINT";
export const API_EXPOSE_ERRORS = "API_EXPOSE_ERRORS";

export const TOKEN_PATH = "TOKEN_PATH";
export const TOKEN_DOMAIN = "TOKEN_DOMAIN";
export const TOKEN_SECRET = "TOKEN_SECRET";
export const ACCESS_TOKEN_AGE_SECONDS = "ACCESS_TOKEN_AGE_SECONDS";
export const REFRESH_TOKEN_AGE_SECONDS = "REFRESH_TOKEN_AGE_SECONDS";

// Graphql
export const GRAPHQL_ALLOW_INTROSPECTION = "GRAPHQL_ALLOW_INTROSPECTION";
export const GRAPHQL_INLINE_TRACE = "GRAPHQL_INLINE_TRACE";

// APIs
export const API_NUMBER_FACT_TOKEN = "API_NUMBER_FACT_TOKEN";

// Database config
export const DATABASE_TYPE = "DATABASE_TYPE";
export const DATABASE_HOST = "DATABASE_HOST";
export const DATABASE_USER = "DATABASE_USER";
export const DATABASE_PORT = "DATABASE_PORT";
export const DATABASE_PASSWORD = "DATABASE_PASSWORD";
export const DATABASE_NAME = "DATABASE_NAME";

// Redis
export const IS_REDIS_USED = "IS_REDIS_USED";
export const REDIS_HOST = "REDIS_HOST";
export const REDIS_PORT = "REDIS_PORT";
export const REDIS_USERNAME = "REDIS_USERNAME";
export const REDIS_PASSWORD = "REDIS_PASSWORD";

// Platform config
export const PLATFORM = "PLATFORM";
export const GOOGLE_CLOUD_SQL_CONNECTION_NAME =
  "GOOGLE_CLOUD_SQL_CONNECTION_NAME";
export const GOOGLE_CLOUD_PROJECT_ID = "GOOGLE_CLOUD_PROJECT_ID";
