name: CI
on: [push]

jobs:
  docker: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image 
      run: docker build -t title .
