name: Version
on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'Boilerplate'
      - run: git config --global user.email 'boilerplate@fraktio.fi'
      - run: npm version patch
      - run: git push